# Generated by Django 5.1.7 on 2025-03-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_attraction_attraction_type_attraction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Large hero image for the attraction page', null=True, upload_to='attractions/covers/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Large hero image for the destination page', null=True, upload_to='destinations/covers/'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Large hero image for the excursion page', null=True, upload_to='excursions/covers/'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for the excursion gallery'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Large hero image for the hotel detail page', null=True, upload_to='hotels/covers/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='List of image URLs for the hotel gallery'),
        ),
    ]
